# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.4'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.0.4', '>= 7.0.4.3'

gem 'aasm'
gem 'activeadmin'
gem 'activeadmin_addons', github: 'platanus/activeadmin_addons'
gem 'active_model_serializers', '~> 0.10.0'
gem 'argon2'
gem 'aws-sdk-s3', require: false
gem 'banking-info', '~> 3.52.30zi', source: 'https://gem.fury.io/remitano/'
gem 'base58'
gem 'cancancan'
gem 'chartkick'
gem 'clockwork'
gem 'connection_pool'
gem 'devise'
gem 'ed25519-hd-rb'
gem 'eth'
gem 'fcm'
gem 'figaro'
gem 'google-apis-analyticsdata_v1beta'
gem 'googleauth'
gem 'grape'
gem 'grape-active_model_serializers'
gem 'grape-entity'
gem 'grape-rails-cache'
gem 'haml-rails', '~> 2.0'
gem 'httparty'
gem 'intercom', '4.0.1'
gem 'jwt'
gem 'kaminari'
gem 'oj'
gem 'openssl', '~> 3.1'
gem 'phonelib'
gem 'rack-attack'
gem 'rack-cors'
gem 'rails-settings-cached', '~> 0.7'
gem 'rbnacl'
gem 'remi-signer'
gem 'rollbar'
gem 'scout_apm'
gem 'rotp'
gem 'sidekiq'
gem 'telegram-bot-ruby', '~> 1.0'
gem 'twilio-ruby', '~> 6.0.2'
gem 'websocket-client-simple'
gem 'ruby-await-node' # https://github.com/remitano/ruby-await-node

source 'https://rubygems.pkg.github.com/remitano' do
  gem 'omniauth-sso'
  gem 'portal-connectors'
  gem 'single_increase_by', '0.0.3'
  gem 'nest-redis', '4.0.1', require: 'nest'
end

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails'

# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 5.6', '>= 5.6.7'

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem 'importmap-rails'

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem 'turbo-rails'

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem 'stimulus-rails'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem 'jbuilder'

# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'paper_trail', '~> 14.0'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# gem "pygments.rb"
gem 'activeadmin_json_editor', '~> 0.0.10'
gem 'activeadmin_simplemde'
gem 'angularjs-rails'
gem 'angular-rails-templates'
gem 'jquery-ui-rails'
gem 'redcarpet'

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem 'active_storage_validations', '~> 1.0'
gem 'image_processing', '~> 1.2'
gem 'montrose', '~> 0.16.0'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'launchy'
  gem 'letter_opener'
  gem 'pry-byebug'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'solargraph'
end

group :test do
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'rails-controller-testing'
  gem 'redis_test'
  gem 'rspec_junit_formatter'
  gem 'rspec-rails'
  gem 'rspec-sidekiq'
  gem 'shoulda-matchers'
  gem 'simplecov'
  gem 'simplecov-json'
  gem 'vcr'
  gem 'webdrivers'
  gem 'webmock', require: false
end

group :development do
  gem 'web-console'
  # Use console on exceptions pages [https://github.com/rails/web-console]

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :development, :test do
  gem 'bullet'
end
