REDIS_URL: redis://localhost:6379/0
REDIS_QUEUE_DEFAULT: background
REDIS_QUEUE_MAILER: mailer
INFURA_API_KEY: 1234567890
INFURA_API_SECRET_KEY: 1234567890
ALCHEMY_API_KEY: 1234567890
ANKR_API_KEY: 1234567890
SLACK_GENERAL_HOOK: https://hooks.slack.com/services/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

EMAIL_SMTP_HOST: smtp.gmail.com
EMAIL_SMTP_PORT: "587"
EMAIL_SMTP_DOMAIN: gmail.com
EMAIL_SMTP_USERNAME: test@gmail.com
EMAIL_SMTP_PASSWORD: uovcmwspfdsdbnqp

ROOT_URL: 127.0.0.1:3969

GITHUB_ACCESS_TOKEN: GITHUB_ACCESS_TOKEN
INTERCOM_TOKEN: INTERCOM_TOKEN
PROPEASY_INTERCOM_TOKEN: PROPEASY_INTERCOM_TOKEN
TELEGRAM_BOT_TOKEN: TELEGRAM_BOT_TOKEN
ROLLBAR_ACCESS_TOKEN: ROLLBAR_ACCESS_TOKEN

REMITANO_ACCESS_KEY: ABCXYZ
REMITANO_SECRET_KEY: ABCXYZ
REMITANO_TWO_FA_SECRET: ABCXYZ
REMITANO_RENEC_ADDR: ABCXYZ

AWS_STAGING02_AS_ACCESS_KEY_ID: xyz
AWS_STAGING02_AS_SECRET_ACCESS_KEY: xyz
AWS_STAGING02_DAILYDAPP_BUCKET: xyz
AWS_STAGING02_REGION: xyz

COIN_WALLET_HOST: "http://localhost:3016"
COIN_WALLET_SECRET: "xxxxxxxxxxxxxxx"
POSTBACK_APP_URL: "http://localhost:3969"
MAX_SECOND_EXCEEDED: 90

SDK_EXECUTOR_API_ACCESS_KEY: "xxxx"
SDK_EXECUTOR_API_SECRET_KEY: "xxxx"
SDK_EXECUTOR_API_REGION: "xxxx"
SDK_EXECUTOR_API_ENDPOINT: "https://xxxx"

ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ""
ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ""
ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ""

TATUM_API_KEY: ""
CMC_API_KEY: ""

P2P_ESCROW_SITE_URL: ""
REMI_ADMIN_SITE_URL: ""

REWIRE_GOOGLE_CLIENT_ID: ""

REMITANO_KYC_SERVICE_APP_NAME: ""
REMITANO_KYC_SERVICE_SECRET: ""
REMITANO_KYC_SERVICE_WEBHOOK_SECRET: ""
REMITANO_ENDPOINT: "https://remitano.com"
REMITANO_API_ENDPOINT: "https://api.remitano.com"

NEMOSWAP_TELEGRAM_BOT_TOKEN: ""

development:
  DATABASE_URL: postgres://localhost:5432/renechub_development
  ROOT_URL: "http://localhost:3969"

test:
  DATABASE_URL: postgres://localhost:5432/renechub_test
  ROOT_URL: "http://localhost:3969"

ZOOM_CLIENT_ID: ""
ZOOM_CLIENT_SECRET: ""
ZOOM_ACCOUNT_ID: ""

TWILIO_ACCOUNT_SID: ENTER_YOUR_TWILIO_ACCOUNT_SID_HERE
TWILIO_AUTH_TOKEN: ENTER_YOUR_TWILIO_ACCOUNT_AUTH_TOKEN_HERE
TWILIO_SERVICE_ID: ENTER_YOUR_TWILIO_SERVICE_ID_HERE

SENDGRID_USERNAME: xxxx
SENDGRID_PASSWORD: xxxx
SENDGRID_MAIL_DOMAIN: xxxx
SENDGRID_MAIL_ADDRESS: xxxx

KYC_ALLOWED_ORIGINS: "http://localhost:3000"

FIFTEEN_FIVE_API_KEY: "FIFFIVE_API_KEY"
CULTURE_BOT_SLACK_SIGNING_SECRET: "CULTURE_BOT_SLACK_SIGNING_SECRET"

LENDING_BACKEND_SERVER: http://localhost:3967
INSTANTWIRE_URL: "http://localhost:3000"
INSTANTWIRE_NOTI_SLACK_HOOK: https://hooks.slack.com/services/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

COINMARKETCAP_API_KEY: "****-***-***-****"